// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_neighbors_vec
IntegerVector get_neighbors_vec(NumericVector x, double epsilon);
RcppExport SEXP _coMDS_get_neighbors_vec(SEXP xSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(get_neighbors_vec(x, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// get_neighbors
List get_neighbors(List Ds, NumericVector epsilon_vec);
RcppExport SEXP _coMDS_get_neighbors(SEXP DsSEXP, SEXP epsilon_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Ds(DsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type epsilon_vec(epsilon_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(get_neighbors(Ds, epsilon_vec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_coMDS_get_neighbors_vec", (DL_FUNC) &_coMDS_get_neighbors_vec, 2},
    {"_coMDS_get_neighbors", (DL_FUNC) &_coMDS_get_neighbors, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_coMDS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
