# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_neighbors_vec <- function(x, epsilon) {
    .Call(`_coMDS_get_neighbors_vec`, x, epsilon)
}

get_neighbors <- function(Ds, epsilon_vec) {
    .Call(`_coMDS_get_neighbors`, Ds, epsilon_vec)
}

